#!/bin/bash
docker exec services_kafka_1 bash opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --partitions 3  --replication-factor 1 --topic CustomerCreate
docker exec services_kafka_1 opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --partitions 3  --replication-factor 1 --topic CustomerUpdate
docker exec services_kafka_1 opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --partitions 3  --replication-factor 1 --topic CustomerDelete
docker exec services_kafka_1 opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --partitions 3  --replication-factor 1 --topic SupplierCreate
docker exec services_kafka_1 opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --partitions 3  --replication-factor 1 --topic SupplierUpdate
docker exec services_kafka_1 opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --partitions 3  --replication-factor 1 --topic SupplierDelete
docker exec services_kafka_1 opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --partitions 3  --replication-factor 1 --topic PurchaseOrderCreate
docker exec services_kafka_1 opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --partitions 3  --replication-factor 1 --topic PurchaseOrderUpdate
docker exec services_kafka_1 opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --partitions 3  --replication-factor 1 --topic PurchaseOrderDelete
docker exec services_kafka_1 opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --partitions 3  --replication-factor 1 --topic UpdatePurchaseOrderProduct
docker exec services_kafka_1 opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --partitions 3  --replication-factor 1 --topic DeletePurchaseOrderProduct
docker exec services_kafka_1 opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --partitions 3  --replication-factor 1 --topic DeliveryNoteCreate
docker exec services_kafka_1 opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --partitions 3  --replication-factor 1 --topic DeliveryNoteUpdate
docker exec services_kafka_1 opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --partitions 3  --replication-factor 1 --topic DeliveryNoteDelete
docker exec services_kafka_1 opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --partitions 3  --replication-factor 1 --topic DeliveryItemDelete
docker exec services_kafka_1 opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --partitions 3  --replication-factor 1 --topic ProductCreate
docker exec services_kafka_1 opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --partitions 3  --replication-factor 1 --topic ProductUpdate
docker exec services_kafka_1 opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --partitions 3  --replication-factor 1 --topic ProductDelete
docker exec services_kafka_1 opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --partitions 3  --replication-factor 1 --topic ProductCategoryCreate
docker exec services_kafka_1 opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --partitions 3  --replication-factor 1 --topic ProductCategoryUpdate
docker exec services_kafka_1 opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --partitions 3  --replication-factor 1 --topic WarehouseIn
docker exec services_kafka_1 opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --partitions 3  --replication-factor 1 --topic WarehouseOut
docker exec services_kafka_1 opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --partitions 3  --replication-factor 1 --topic WarehouseTranfer
docker exec services_kafka_1 opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --partitions 3  --replication-factor 1 --topic InvoiceCreate
docker exec services_kafka_1 opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --partitions 3  --replication-factor 1 --topic InvoiceUpdate
docker exec services_kafka_1 opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --partitions 3  --replication-factor 1 --topic InvoiceDelete
docker exec services_kafka_1 opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --partitions 3  --replication-factor 1 --topic SalesOrderCreate
docker exec services_kafka_1 opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --partitions 3  --replication-factor 1 --topic SalesOrderUpdate
docker exec services_kafka_1 opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --partitions 3  --replication-factor 1 --topic SalesOrderDelete
docker exec services_kafka_1 opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --partitions 3  --replication-factor 1 --topic XeroInvoiceCreate
docker exec services_kafka_1 opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --partitions 3  --replication-factor 1 --topic XeroInvoiceUpdate
docker exec services_kafka_1 opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --partitions 3  --replication-factor 1 --topic SPCreate
docker exec services_kafka_1 opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --partitions 3  --replication-factor 1 --topic ShippingUpdate
docker exec services_kafka_1 opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --partitions 3  --replication-factor 1 --topic ShippingDelete
docker exec services_kafka_1 opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --partitions 3  --replication-factor 1 --topic ReceivePaymentCreate
docker exec services_kafka_1 opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --partitions 3  --replication-factor 1 --topic ReceivePaymentUpdate
docker exec services_kafka_1 opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --partitions 3  --replication-factor 1 --topic ReceivePaymentDelete
docker exec services_kafka_1 opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --partitions 3  --replication-factor 1 --topic CustomerShopCreate
docker exec services_kafka_1 opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --partitions 3  --replication-factor 1 --topic CustomerShopUpdate
docker exec services_kafka_1 opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --partitions 3  --replication-factor 1 --topic CustomerShopDelete
docker exec services_kafka_1 opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --partitions 3  --replication-factor 1 --topic SOUpdate
docker exec services_kafka_1 opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --partitions 3  --replication-factor 1 --topic POUpdate
docker exec services_kafka_1 opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --partitions 3  --replication-factor 1 --topic SOCreate
docker exec services_kafka_1 opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --partitions 3  --replication-factor 1 --topic SOUpdate1
docker exec services_kafka_1 opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --partitions 3  --replication-factor 1 --topic SalesOrderItemCreate
docker exec services_kafka_1 opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --partitions 3  --replication-factor 1 --topic SalesOrderItemUpdate
docker exec services_kafka_1 opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --partitions 3  --replication-factor 1 --topic SalesOrderItemDelete
docker exec services_kafka_1 opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --partitions 3  --replication-factor 1 --topic SOWebhook
docker exec services_kafka_1 opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --partitions 3  --replication-factor 1 --topic CheckKafka
docker exec services_kafka_1 opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --partitions 3  --replication-factor 1 --topic XeroWebhook