version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - '2181:2181'
  kafka:
    image: wurstmeister/kafka
    ports:
      - '9092:9092'
    environment:
      DEBUG: kafka-node:*
      KAFKA_ADVERTISED_HOST_NAME: 'localhost'
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    depends_on:
      - mongo
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        CLUSTER_PUBLIC_KEY: erp.com
        databases:
          default:
            connector: mongo
            uri: mongodb://prisma:prisma@mongo
  mongo:
    image: mongo:3.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: prisma
      MONGO_INITDB_ROOT_PASSWORD: prisma
    ports:
      - '27017:27017'
    volumes:
      - mongo:/var/lib/mongo
volumes:
  mongo: ~
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
