apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: sms-delivery
  name: sms-delivery
  namespace: erp
spec:
  ports:
    - name: '3009'
      port: 3009
      targetPort: 3009
  selector:
    io.kompose.service: sms-delivery
status:
  loadBalancer: {}
