apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: sms-invoice
  name: sms-invoice
  namespace: erp
spec:
  ports:
    - name: '3008'
      port: 3008
      targetPort: 3008
  selector:
    io.kompose.service: sms-invoice
status:
  loadBalancer: {}
