apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: sms-warehouse
  name: sms-warehouse
  namespace: erp
spec:
  ports:
    - name: '3001'
      port: 3001
      targetPort: 3001
  selector:
    io.kompose.service: sms-warehouse
status:
  loadBalancer: {}
