apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.production.yml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: sms-gateway
  name: sms-gateway
  namespace: erp
spec:
  type: NodePort
  ports:
    - name: '4000'
      port: 4000
      targetPort: 4000
  selector:
    io.kompose.service: sms-gateway
status:
  loadBalancer: {}
