apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: sms-user
  name: sms-user
  namespace: erp
spec:
  ports:
    - name: '3014'
      port: 3014
      targetPort: 3014
  selector:
    io.kompose.service: sms-user
status:
  loadBalancer: {}
