apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: sms-product
  name: sms-product
  namespace: erp
spec:
  ports:
    - name: '3003'
      port: 3003
      targetPort: 3003
  selector:
    io.kompose.service: sms-product
status:
  loadBalancer: {}
