#!/bin/bash

kubectl --namespace erp exec -it kafka-client -- kafka-topics.sh --create --zookeeper kafka-zookeeper:2181 --replication-factor 2 --partitions 2 --topic CustomerCreate
kubectl --namespace erp exec -it kafka-client -- kafka-topics.sh --create --zookeeper kafka-zookeeper:2181 --replication-factor 2 --partitions 2 --topic CustomerUpdate
kubectl --namespace erp exec -it kafka-client -- kafka-topics.sh --create --zookeeper kafka-zookeeper:2181 --replication-factor 2 --partitions 2 --topic CustomerDelete
kubectl --namespace erp exec -it kafka-client -- kafka-topics.sh --create --zookeeper kafka-zookeeper:2181 --replication-factor 2 --partitions 2 --topic SupplierCreate
kubectl --namespace erp exec -it kafka-client -- kafka-topics.sh --create --zookeeper kafka-zookeeper:2181 --replication-factor 2 --partitions 2 --topic SupplierUpdate
kubectl --namespace erp exec -it kafka-client -- kafka-topics.sh --create --zookeeper kafka-zookeeper:2181 --replication-factor 2 --partitions 2 --topic SupplierDelete
kubectl --namespace erp exec -it kafka-client -- kafka-topics.sh --create --zookeeper kafka-zookeeper:2181 --replication-factor 2 --partitions 2 --topic PurchaseOrderCreate
kubectl --namespace erp exec -it kafka-client -- kafka-topics.sh --create --zookeeper kafka-zookeeper:2181 --replication-factor 2 --partitions 2 --topic POUpdate
kubectl --namespace erp exec -it kafka-client -- kafka-topics.sh --create --zookeeper kafka-zookeeper:2181 --replication-factor 2 --partitions 2 --topic PurchaseOrderDelete
kubectl --namespace erp exec -it kafka-client -- kafka-topics.sh --create --zookeeper kafka-zookeeper:2181 --replication-factor 2 --partitions 2 --topic UpdatePurchaseOrderProduct
kubectl --namespace erp exec -it kafka-client -- kafka-topics.sh --create --zookeeper kafka-zookeeper:2181 --replication-factor 2 --partitions 2 --topic DeletePurchaseOrderProduct
kubectl --namespace erp exec -it kafka-client -- kafka-topics.sh --create --zookeeper kafka-zookeeper:2181 --replication-factor 2 --partitions 2 --topic DeliveryNoteCreate
kubectl --namespace erp exec -it kafka-client -- kafka-topics.sh --create --zookeeper kafka-zookeeper:2181 --replication-factor 2 --partitions 2 --topic DeliveryNoteUpdate
kubectl --namespace erp exec -it kafka-client -- kafka-topics.sh --create --zookeeper kafka-zookeeper:2181 --replication-factor 2 --partitions 2 --topic DeliveryNoteDelete
kubectl --namespace erp exec -it kafka-client -- kafka-topics.sh --create --zookeeper kafka-zookeeper:2181 --replication-factor 2 --partitions 2 --topic DeliveryItemDelete
kubectl --namespace erp exec -it kafka-client -- kafka-topics.sh --create --zookeeper kafka-zookeeper:2181 --replication-factor 2 --partitions 2 --topic ProductCreate
kubectl --namespace erp exec -it kafka-client -- kafka-topics.sh --create --zookeeper kafka-zookeeper:2181 --replication-factor 2 --partitions 2 --topic ProductUpdate
kubectl --namespace erp exec -it kafka-client -- kafka-topics.sh --create --zookeeper kafka-zookeeper:2181 --replication-factor 2 --partitions 2 --topic ProductDelete
kubectl --namespace erp exec -it kafka-client -- kafka-topics.sh --create --zookeeper kafka-zookeeper:2181 --replication-factor 2 --partitions 2 --topic ProductCategoryCreate
kubectl --namespace erp exec -it kafka-client -- kafka-topics.sh --create --zookeeper kafka-zookeeper:2181 --replication-factor 2 --partitions 2 --topic ProductCategoryUpdate
kubectl --namespace erp exec -it kafka-client -- kafka-topics.sh --create --zookeeper kafka-zookeeper:2181 --replication-factor 2 --partitions 2 --topic WarehouseIn
kubectl --namespace erp exec -it kafka-client -- kafka-topics.sh --create --zookeeper kafka-zookeeper:2181 --replication-factor 2 --partitions 2 --topic WarehouseOut
kubectl --namespace erp exec -it kafka-client -- kafka-topics.sh --create --zookeeper kafka-zookeeper:2181 --replication-factor 2 --partitions 2 --topic WarehouseTranfer
kubectl --namespace erp exec -it kafka-client -- kafka-topics.sh --create --zookeeper kafka-zookeeper:2181 --replication-factor 2 --partitions 2 --topic InvoiceCreate
kubectl --namespace erp exec -it kafka-client -- kafka-topics.sh --create --zookeeper kafka-zookeeper:2181 --replication-factor 2 --partitions 2 --topic InvoiceUpdate
kubectl --namespace erp exec -it kafka-client -- kafka-topics.sh --create --zookeeper kafka-zookeeper:2181 --replication-factor 2 --partitions 2 --topic InvoiceDelete
kubectl --namespace erp exec -it kafka-client -- kafka-topics.sh --create --zookeeper kafka-zookeeper:2181 --replication-factor 2 --partitions 2 --topic SOCreate
kubectl --namespace erp exec -it kafka-client -- kafka-topics.sh --create --zookeeper kafka-zookeeper:2181 --replication-factor 2 --partitions 2 --topic SOUpdate1
kubectl --namespace erp exec -it kafka-client -- kafka-topics.sh --create --zookeeper kafka-zookeeper:2181 --replication-factor 2 --partitions 2 --topic SalesOrderDelete
kubectl --namespace erp exec -it kafka-client -- kafka-topics.sh --create --zookeeper kafka-zookeeper:2181 --replication-factor 2 --partitions 2 --topic XeroInvoiceCreate
kubectl --namespace erp exec -it kafka-client -- kafka-topics.sh --create --zookeeper kafka-zookeeper:2181 --replication-factor 2 --partitions 2 --topic XeroInvoiceUpdate
kubectl --namespace erp exec -it kafka-client -- kafka-topics.sh --create --zookeeper kafka-zookeeper:2181 --replication-factor 2 --partitions 2 --topic SPCreate
kubectl --namespace erp exec -it kafka-client -- kafka-topics.sh --create --zookeeper kafka-zookeeper:2181 --replication-factor 2 --partitions 2 --topic ShippingUpdate
kubectl --namespace erp exec -it kafka-client -- kafka-topics.sh --create --zookeeper kafka-zookeeper:2181 --replication-factor 2 --partitions 2 --topic ShippingDelete
kubectl --namespace erp exec -it kafka-client -- kafka-topics.sh --create --zookeeper kafka-zookeeper:2181 --replication-factor 2 --partitions 2 --topic ReceivePaymentCreate
kubectl --namespace erp exec -it kafka-client -- kafka-topics.sh --create --zookeeper kafka-zookeeper:2181 --replication-factor 2 --partitions 2 --topic ReceivePaymentUpdate
kubectl --namespace erp exec -it kafka-client -- kafka-topics.sh --create --zookeeper kafka-zookeeper:2181 --replication-factor 2 --partitions 2 --topic ReceivePaymentDelete
kubectl --namespace erp exec -it kafka-client -- kafka-topics.sh --create --zookeeper kafka-zookeeper:2181 --replication-factor 2 --partitions 2 --topic CustomerShopCreate
kubectl --namespace erp exec -it kafka-client -- kafka-topics.sh --create --zookeeper kafka-zookeeper:2181 --replication-factor 2 --partitions 2 --topic CustomerShopUpdate
kubectl --namespace erp exec -it kafka-client -- kafka-topics.sh --create --zookeeper kafka-zookeeper:2181 --replication-factor 2 --partitions 2 --topic CustomerShopDelete
kubectl --namespace erp exec -it kafka-client -- kafka-topics.sh --create --zookeeper kafka-zookeeper:2181 --replication-factor 2 --partitions 2 --topic SalesOrderItemUpdate
kubectl --namespace erp exec -it kafka-client -- kafka-topics.sh --create --zookeeper kafka-zookeeper:2181 --replication-factor 2 --partitions 2 --topic SalesOrderItemCreate
kubectl --namespace erp exec -it kafka-client -- kafka-topics.sh --create --zookeeper kafka-zookeeper:2181 --replication-factor 2 --partitions 2 --topic SalesOrderItemDelete
kubectl --namespace erp exec -it kafka-client -- kafka-topics.sh --create --zookeeper kafka-zookeeper:2181 --replication-factor 2 --partitions 2 --topic SOWebhook
kubectl --namespace erp exec -it kafka-client -- kafka-topics.sh --create --zookeeper kafka-zookeeper:2181 --replication-factor 2 --partitions 2 --topic CheckKafka